services:
  vault-fetcher:
    build: ./vault-fetcher
    env_file:
      - ./instance/.env
    volumes:
      - ./instance:/app/instance:rw  # Changed to host mount
    command: python fetch_secrets.py
    restart: "no"

  devdox:
    build: ./devdox
    env_file:
      - ./instance/.env
    depends_on:
      - vault-fetcher
    volumes:
      - ./data/migrations:/data/migrations
      - ./instance:/app/instance:ro
      - ./logs:/app/logs
    ports:
      - "8000:8000"
    command: sh -c "while [ ! -f /app/instance/.env ]; do sleep 1; done && ./entrypoint.sh"
