AUTH_FAILED = "Access denied. Please log in again."
INVALID_BEARER_TOKEN_SCHEMA = "Missing or malformed Authorization header"
SERVICE_UNAVAILABLE = "Service temporarily unavailable. Please try again later."
GENERIC_BAD_REQUEST = "Bad Request"
TOKEN_MISSING = "Invalid Token or missing"
GENERIC_RESOURCE_NOT_FOUND = "Resource Not Found"
USER_RESOURCE_NOT_FOUND = "User Not Found"
GIT_LABEL_TOKEN_RESOURCE_NOT_FOUND = "Git Label Token Not Found"
GENERIC_ALREADY_EXIST = "Already Exists"
REPOSITORY_ALREADY_EXISTS = "Repository Already Exists"
TOKEN_NOT_FOUND = "Token not found"

MISSING_USER_ID_TITLE = "MISSING_USER_ID"
MISSING_USER_ID_LOG_MESSAGE = "user_id was None when trying to fetch Git labels."

MISSING_LABEL_ID_TITLE = "MISSING_LABEL"
MISSING_LABEL_LOG_MESSAGE = "label was None when trying to fetch Git labels."

UNIQUE_API_KEY_GENERATION_FAILED = "Could not generate a unique API key, please try again."
FAILED_GENERATE_API_KEY_RETRIES_LOG_MESSAGE = "Failed to generate a unique API key after {attempts} attempts"