name: Build
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarqube:
    name: SonarQube
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12  # or your actual version
      
      - name: Install dependencies
        working-directory: devdox
        run: |
          python -m pip install --upgrade pip
          pip install .[dev]
          pip install coverage

      - name: Build Docker image
        run: docker compose build

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.28.0
        env:
          TRIVY_DISABLE_VEX_NOTICE: "true"
        with:
            image-ref: devdox:latest
            format: 'table'
            severity: 'CRITICAL,HIGH'  # Only fail on high/critical, ignore medium
            exit-code: '1'  # Fail the build if vulnerabilities found

      - name: Run tests and generate coverage
        working-directory: devdox
        run: |
          coverage run -m pytest tests
          coverage xml

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

